id: P002954
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14992
  title: ཕུག་བྲག་བཀའ་འགྱུར་གྱི་དཀར་ཆག
  author: ''
  volumes:
    9b00f85f67c9474bb354a94771b2bb08:
      image_group_id: I1KG14995
      title: ''
      volume_number: 1
      total_pages: 148
